apiVersion: apps/v1
kind: Deployment
metadata:
  name: ministry-of-magic
spec:
  selector:
    matchLabels:
      app: ministry-of-magic
  replicas: 2
  template:
    metadata:
      labels:
        app: ministry-of-magic
    spec:
      containers:
        - name: ministry-of-magic
          image: puneeth0/ministry-of-magic
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084