apiVersion: v1
kind: Service
metadata:
  name: ministry-of-magic-svc
spec:
  selector:
    app: ministry-of-magic
  ports:
    - protocol: "TCP"
      port: 8084
      targetPort: 8084
  type: NodePort